# Generated by Django 6.0.3 on 2026-03-23 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vessel',
            fields=[
                ('mmsi', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('date_entry', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='VesselInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imo', models.CharField(blank=True, max_length=10, null=True)),
                ('vessel_name', models.CharField(blank=True, max_length=50, null=True)),
                ('year_of_build', models.IntegerField(blank=True, null=True)),
                ('flag', models.CharField(blank=True, max_length=50, null=True)),
                ('dwt', models.FloatField(blank=True, null=True)),
                ('teu_capacity', models.FloatField(blank=True, null=True)),
                ('draft', models.FloatField(blank=True, null=True)),
                ('loa', models.FloatField(blank=True, null=True)),
                ('lbp', models.FloatField(blank=True, null=True)),
                ('breadth_extreme', models.FloatField(blank=True, null=True)),
                ('breadth_moulded', models.FloatField(blank=True, null=True)),
                ('vessel_type', models.CharField(blank=True, max_length=100, null=True)),
                ('mmsi', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.vessel')),
            ],
        ),
    ]
